### ISSUE TITLE
Getting this error in kots-api pod. Due to which cant open admin console.

### ISSUE THREAD

**Issue by yuvraj9** [replicatedhq/kots#658]
This one had 2 apps installed which are same apps. We wanted to delete one of them but there was no option to delete apps. I am getting this error in kotsadmin-api pod. This results in admin console not opening.

Since admin console is not opening I cant share support bundle either.

Logs-
```
    stack: "NoSuchKey: The specified key does not exist.\n    at Request.extractError (/src/node_modules/aws-sdk/lib/services/s3.js:585:35)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/src/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/src/node_modules/aws-sdk/lib/event_listeners.js:299:13)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)"
NoSuchKey: The specified key does not exist.
    at Request.extractError (/src/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10
ERROR [ 2020-06-16T11:07:51.083Z] (kotsadm-api/1 on kotsadm-api-dd4d94d86-25fr8): The specified key does not exist.
    error: {
      "message": "The specified key does not exist.",
      "locations": [
        {
          "line": 12,
          "column": 7
        }
      ],
      "path": [
        "listApps",
        "kotsApps",
        1,
        "allowSnapshots"
      ]
    }
    stack: "NoSuchKey: The specified key does not exist.\n    at Request.extractError (/src/node_modules/aws-sdk/lib/services/s3.js:585:35)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/src/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/src/node_modules/aws-sdk/lib/event_listeners.js:299:13)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)"
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/src/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/src/node_modules/aws-sdk/lib/event_listeners.js:299:13)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
NoSuchKey: The specified key does not exist.
    at Request.extractError (/src/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/src/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/src/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/src/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/src/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/src/node_modules/aws-sdk/lib/event_listeners.js:299:13)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
(node:1) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND kotsadm-postgres kotsadm-postgres:5432
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by areed** [comment]
I've seen similar errors before when an app was partially installed (license uploaded but pulling the application failed.) The only solution in that case was to remove the kotsadm namespace and reinstall.

**Comment by yuvraj9** [comment]
@areed The app was working fine and we were using it for 2 weeks then suddenly we faced this error.

**Comment by emosbaugh** [comment]
Could you run the following to generate a support bundle?

```
kubectl support-bundle https://kots.io 
```

**Comment by yuvraj9** [comment]
Support bundle ID - suitably-driving-condor

**Comment by emosbaugh** [comment]
im seeing ```{
          "type": "MemoryPressure",
          "status": "True",
          "lastHeartbeatTime": "2020-06-25T10:16:09Z",
          "lastTransitionTime": "2020-06-25T10:16:09Z",
          "reason": "KubeletHasInsufficientMemory",
          "message": "kubelet has insufficient memory available"
        },```

**Comment by yuvraj9** [comment]
This issue happened to 3 of our clusters and we had to redeploy kots in them. Few things we have tried here- We increased the pvc size of minio to 10GB as in one of our cluster got the errror that minio was running out of space but unfortunately this didnt work.

**Comment by dexhorthy** [comment]
@emosbaugh @yuvraj9  is this one okay to close? It sounds like the issue was related to insufficient memory?

**Comment by emosbaugh** [comment]
It seems that the minio pvc ran out of space and then kots gets into an unrecoverable state because there is an entry in the db but no matching one in the object store. It may be possible to insert the version into the db only after we save it in the object store. I'm not sure if we should close this until that is fixed.
